name: Tests

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 7.3]
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} (${{ matrix.dependency-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extension: dom, libxml
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit
